### PR TITLE
compatible to 2018-04-22 "Greebo", no link

### PR DESCRIPTION
**Pull request by unixhex**
* function call compatible to dokuwiki 2018-04-22 greebo
* removed info and advertising links to sixxs.net, since that service no longer exists :-(
*  `~~YOURIP_IPONLY~~` adds only the ip without text

### CODE REVIEW

**Comment by artem-sidorenko** [comment]
@unixhex thanks for this PR! I'm not really maintaining this plugin anymore, I'm happy to add you as co-maintainer if you like:)

**Comment by artem-sidorenko** [comment]
..or I can also transfer the entire repository

**Comment by unixhex** [comment]
Hi @artem-sidorenko,

If you want to keep a "toe in the pond", I'd agree to be your co-maintainer.
If you prefer to walk out of it (because e.g. you don't use it any more)
I would also agree to adopt your brain-child :-)

Best wishes,
Hella

**Comment by artem-sidorenko** [comment]
@unixhex I'm happy to transfer it :-) Can you please rename your fork? Because `unixhex/dokuwiki-yourip already exists`...

**Comment by unixhex** [comment]
renamed my fork, swept the place, opened the window for fresh air (d*mn, it is raining), waiting for a new resident :-)

**Comment by artem-sidorenko** [comment]
`unixhex already has a repository in the artem-sidorenko/dokuwiki-yourip network`...
I guess you have to remove the fork completely...hrr

**Comment by unixhex** [comment]
Unluckily you are right, the [doku](https://help.github.com/en/articles/transferring-a-repository) says:
"The target account must not have a repository with the same name, or a fork in the same network."
I've deleted my fork here ...

**Comment by artem-sidorenko** [comment]
thanks for taking over the maintenance!:)

**Pull request merged**
